### ISSUE TITLE
Crashing for missing railcraft API

### ISSUE THREAD

**Issue by EzerArch** [EternalBlueFlame/Traincraft-5#166] opened 2016-09-19 06:02 UTC
I'm getting "NoClassDefFoundError: railcraft api" every time I right-click some vehicles, esp. cargo ones, with an item in hand and if I use the Stake. (EDITED)

Probably the crash is caused by a dependency leftover related to railcraft's crowbar, which gets exposed once I don't have railcraft installed.

```
Description: Unexpected error

java.lang.NoClassDefFoundError: mods/railcraft/api/core/items/IToolCrowbar
    at train.common.api.EntityRollingStock.func_130002_c(EntityRollingStock.java:1667)
    at train.common.entity.rollingStock.EntityTracksBuilder.func_130002_c(EntityTracksBuilder.java:323)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
*snip*
Caused by: java.lang.ClassNotFoundException: mods.railcraft.api.core.items.IToolCrowbar
```

Full log: https://gist.github.com/EzerArch/b059b46c2c552ec423658758a2dd738f

**Situation:** The builder and cargo vehicles will crash if I right-click them with an item in hand. Right-clicking with bare hand won't crash.

Forge 10.13.4.1614
TC version: Traincraft-4.3.0_003

**Comment by canitzp** [comment] 2016-09-19 07:18
You're correct, at the method we use railcraft classes without asking that the class exist / railcraft is present

**Comment by NitroxydeX** [comment] 2016-09-19 10:04
Closed via 1487431e8656d39bf1d3fd26628c34db28a5835a

**Closed as completed by NitroxydeX** 2016-09-19 10:04 UTC

**Comment by EzerArch** [comment] 2016-09-19 21:58
Additional info:

> I'm getting "NoClassDefFoundError: railcraft api" every time I right-click some vehicles, esp. cargo ones, **_with an item in hand and if I use the Stake_**.

**Comment by NitroxydeX** [comment] 2016-09-19 22:37
@EzerArch well I couldn't reproduce it. Anyways the crash shouldn't happen because we ship with the RC-API. It seems that you have an other mod with an old RC Api thats overwriting our used API. But I just fixed the problem in the next release
