### ISSUE TITLE
Slope Track Bug

### ISSUE THREAD

**Issue by ccgfok** [EternalBlueFlame/Traincraft-5#221] opened 2016-12-08 03:50 UTC
When the locomotive start running at the 4th place of slope track, locomotive will turn 90 degress to left, also reach over the limit.
Gif file: gfycat.com/WanJoyfulAmericanratsnake

**Comment by NitroxydeX** [comment] 2016-12-08 16:13
Duplicate of #216

**Closed as completed by NitroxydeX** 2016-12-08 16:13 UTC
Labels: duplicate
