### ISSUE TITLE
Cannot lock passenger cars

### ISSUE THREAD

**Issue by axelpx** [EternalBlueFlame/Traincraft-5#179] opened 2016-09-25 19:26 UTC
Is there a way to lock them and prevent from being broken by other players? 
If you lock a locomotive its doesn't lock the whole train, only a locomotive itself.

Minecraft 1.7.10
Mod version: Traincraft-4.3.0_003

**Comment by MacTirom** [comment] 2016-09-26 10:26
With the composite wrench.

**Comment by NitroxydeX** [comment] 2016-09-26 10:29
Yes there is but it is buggy in _003. But is already fixed in _004 (the next release)
duplicate of #147

**Closed as completed by NitroxydeX** 2016-09-26 10:29 UTC
Labels: duplicate
