### ISSUE TITLE
[Suggestion] Over-head stuff for trains

### ISSUE THREAD

**Issue by GazbonicAcid** [EternalBlueFlame/Traincraft-5#253] opened 2017-02-22 17:30 UTC
I would like to request overhead lines that can charge electric trains.
As well as an overhead water tower and tinder equivalent for steam locomotives and their tinder cars.

**Comment by NitroxydeX** [comment] 2017-02-22 18:02
Duplicate of #49 
and
Duplicate of #230

**Closed as completed by NitroxydeX** 2017-02-22 18:02 UTC
Labels: duplicate

**Comment by GazbonicAcid** [comment] 2017-02-22 18:12
Not quite a duplicate of #49 
#49 suggests them as decoration.
I suggested functional ones.
Though it's close enough I need to post there I want them to be functional.

**Comment by NitroxydeX** [comment] 2017-02-22 18:12
It's a duplicate because it is about the overhead lines. We explained in there why it is hard to get functional overhead wires.

**Comment by EternalBlueFlame** [comment] 2017-02-22 19:14
Actually if you read the linked forum post, #49 doesn't state them to be decoration, it requests for them to be functional like they used to be when the feature was being tested. #230 is also suggesting them as functional.

Either way it's not something to deal with till the rewrite, TC's tile entity system is crazy inefficient and there's basically nothing that can be done besides throw all of it out and start over.
Especially the overhead lines part, the chunkloading that would be necessary for it to work with the current system would hurt server performance more than archimedes ships.
Thus the reason why Mr. Brutal removed it in the first place.

The stuff will come in time I assure you, but there's no place for it in the port, too much work for the horrible results we would get.
