### ISSUE TITLE
trains bug out when restarting world

### ISSUE THREAD

**Issue by traso56** [EternalBlueFlame/Traincraft-5#357] opened 2018-01-09 04:56 UTC
before everytime i restarted the world the trains would just mess up and i had to fix them every world restart and it suddently fixed itself but it started to happen again after upgrading my GPU, what happened? 
![Alt Text](https://i.imgur.com/07s1GIS.png)
  
using 014

**Comment by quentfr21** [comment] 2018-01-09 16:33
hello

duplicate of issue #320 (know long standing bug with nbt)

**Comment by traso56** [comment] 2018-01-09 17:49
but it used to work just fine and also the trains are locked meaning even if I remove all carts except for one you can't move it either and if you destroy the track underneath it then the world eats it forever

**Comment by EternalBlueFlame** [comment] 2018-01-09 18:10
yeah it's a dupe of 320, and several dozen other reports.

Nothing related to the systems has changed, it just randomly breaks, it's not related to the server's hardware, although shutting down without actually quitting or using the stop command can make it more likely to happen.
I only found out _exactly_ why this happens recently, the main problem is instead of using the UUID system, TC has it's own ID system which isn't reliable, add that to a number of variables being written to NBT but not actually read which can randomly cause byte buffer read errors.
The latter is fixed in 015, but the core ID thing is still a problem that I can't really address without a rewrite, unless i make the related code 3 times as big to use the old system as a backup and implement a proper one, but even as a backup the old code will still be able to break it, so that's a lot of work for running around in circles.

**Comment by traso56** [comment] 2018-01-09 18:24
oh well that there seems like a really hard to fix bug but i'm sad because it used to work just fine :(

**Comment by EternalBlueFlame** [comment] 2018-01-10 00:19
yeah, it's a pretty random bug, some people never get it, others get it on a regular basis.

I can't even tell you how hard of a time i have replicating it to even attempt to figure out what it was.
Didn't actually figure out what it was till i stumbled across the code that was rather obviously causing it.

**Comment by traso56** [comment] 2018-01-13 04:42
if you need any testers just tell me i can help just tell me also a workaround is to detach trains to only 2 linked carts when you are going to restart, it helped me

**Comment by EternalBlueFlame** [comment] 2018-01-13 23:18
The issue with the port is testers have to be able to compile the mod themselves (this wont be an issue with the rewrite), but if you can do that, yeah, we can use all the hands on deck we can get, lol.

**Closed as completed** 2018-02-04 19:43 UTC
Labels: duplicate
