### ISSUE TITLE
Various Automation Improvements

### ISSUE THREAD

**Issue by CaptainTransportation** [EternalBlueFlame/Traincraft-5#267] opened 2017-04-24 16:38 UTC
I think that the weakest point of traincraft is it's automatability.  The speed control tracks that are included in the mod barely work, if at all, specifically the train stop track. (Instead of launching the train to it's previous speed, the train slowly inches off the launcher.)

My suggestions are:
-Have TC's 3D rails compatible with railcraft signals and vanilla carts (not essential, but would be usefull if it worked)
-Instead of having a train's speed changed by it's surroundings, have a railcraft-style system where the player "selects" a speed by pressing W or S.  The speed will still be measured in kp/h.  Nothing else should be able to change the speed of a train, apart from booster/powered rails.  A powered booster rails should be the same as a player pressing W, and an unpowered one the same as a player pressing S.
-There should be 3D rails that can stop, start, and control the speed of trains.  There should also be tracks that work with carts (loading, unloading, stock car, etc.)
-Try to cut back on FPS lag with the 3D tracks.
-Add an option to measure speed in m/s and mph.
-Add an option to disable the "weight pulled" system.

**Comment by NitroxydeX** [comment] 2017-04-24 18:08
Let me sum this up for you:

We will not make our rails compatible for vanilla carts because it would require us to do ASM which is kinda the worst thing you can do to Minecraft since there are many other mods out there that could break shit with our ASM and the Forge guys kinda like it when you don't use ASM.

Railcrafts Signals are not inside the Railcraft API - thats why we can't make them compatible to our TC rails (which will be possible with 1.10.2+ Railcraft because the author changed the system how it works)

Simple press W/S is no solution for us. This is really against Traincrafts philosophy how the train system works. And to be fair: it's already kinda working like that. You press w to speed up and stay at this speed. There is no really influence from the outside atm beside bugs.

3D-rails with extended functionality are planned for the future (likely in 1.11.2+)

FPS lag for 3D tracks is reduced to nearly zero with the rewrite for 1.11.2 (we really can't change the shit in 1.7.10 because of the bad Tile Entity handling)

Adding option to change between km/h and mph should be easy for the rewrite.

The weight pulled system will never have a switch off since it's like the speed thing not compatible with Traincrafts philosophy how this system is working.


I will close this issue since it doesn't really provide us something new or features anything we should do with Traincraft.

**Closed as completed by NitroxydeX** 2017-04-24 18:08 UTC
Labels: invalid

**Comment by EternalBlueFlame** [comment] 2017-04-24 21:22
I have a little bit of a different opinion on this than nitro.

We cant do the vanilla minecart support in the port because the rails barley work as it is. However support for them is planned in the rewrite (it is actually possible to do it without ASM, but it has to be handled VERY differently from how it is now).

i agree with the signals part, it's not in their API so theres little we can do.

The W ans S controls like you describe was never how traincraft was intended to be played, and it's very unrealistic to a point that would probably be controversial among the community.

3D rails, again, what we have now barley works, but it's planned for the rewrite.

The lag with 3d rails is due to the design of the system, another issue we can't handle till the rewrite.

An mp/h option will be an option in the rewrite's config.

the weight pulled system is just a reiteration of your W and S controls, so it gets the same response.
