### ISSUE TITLE
Trains with wagons derail after getting out of visible chunks

### ISSUE THREAD

**Issue by AlphaStep** [EternalBlueFlame/Traincraft-5#398] opened 2018-06-17 12:24 UTC
![2018-06-17_14 21 41](https://user-images.githubusercontent.com/19998547/41507769-d3880180-7239-11e8-8ebf-f9213a4bf11c.png)
So every time the train gets out of my visible chunks it derails with all the wagons.  this doesn't happen when it's a standalone locomotive. The chunk loading feature is on (this already happened in the 014 update).

**Comment by broscolotos** [comment] 2018-06-17 12:28
We are aware of that bug. It is not fixable in the port, but it is fixed in the rewrite. (If I remember correctly), it is caused due to the rolling-stock having only one hitbox, so it is unaware of its rotation when the chunk is loaded back up. again, not sure if that is the reason, but I believe that is it.

**Comment by EternalBlueFlame** [comment] 2018-06-17 14:21
The issue is due to some degree of NBT corruption in the entities and unreliable chunkloading.
017 makes some fixes for these, but due to the messy nature of TC's code, the rewrite will be the only complete fix.

Also this is a duplicate of #250

**Comment by AlphaStep** [comment] 2018-06-17 16:49
Ah okay, well for some reason it will work (90% of the time) when you place the locomotive behind the wagons.

**Closed as completed** 2018-06-18 17:16 UTC
Labels: duplicate
