### ISSUE TITLE
Typo error in editing out A4 , missed a line . Will not compile unless a manual edit is done

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#311] opened 2017-09-04 15:36 UTC
`/*tenderA4("Tender A4 Mallard", EntityTenderA4.class, 54, ItemIDs.minecartLocoA4MallardTender.item,
 			"tender", 0, 0, 0.2, 0, 0, 0, 0, 0, 6000, new String[] { "Blue", "Lime", "Black", "Green", "White" }, 18,
-			0, 0.98, 0.98, new String[] { "Water capacity: 6000mb" }),
+			0, 0.98, 0.98, new String[] { "Water capacity: 6000mb" }),*/`
Commented Out Line above but still referenced in other module 

`****************************
 Powered By MCP:             
 http://modcoderpack.com/    
 Searge, ProfMobius, Fesh0r, 
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown
****************************
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\Users\ASUS\Dev\tc\build\sources\java\train\common\entity\rollingStock\EntityTenderA4.java:21: error: cannot find symbol
		super(world, FluidRegistry.WATER, 0, EnumTrains.tenderA4.getTankCapacity(), LiquidManager.WATER_FILTER);
		                                               ^
  symbol:   variable tenderA4
  location: class EnumTrains
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
1 warning
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.447 secs`

**Comment by EternalBlueFlame** [comment] 2017-09-04 19:15
the issue is caused from the A4 tender class making a reference to the registry entry which has been commented out.
I already have this fixed in my local repo, i'll upload the changes later today

**Closed as completed** 2017-09-05 22:30 UTC
