### ISSUE TITLE
Ticking Entity - Can't place trains

### ISSUE THREAD

**Issue by Doomragnar** [EternalBlueFlame/Traincraft-5#232] opened 2017-01-17 20:48 UTC
Hi, I can't place any trains or wagons on tracks. Every time I try to do so I get the ticking entity error listed below. I tried generating new worlds as well as checking for bad chunks and that doesn't seem to be the problem.

"
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 17-01-2017 20:42
Description: Ticking entity

java.lang.NoSuchMethodError: mods.railcraft.api.tracks.RailTools.isRailBlockAt(Lnet/minecraft/world/IBlockAccess;III)Z
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:885)
	at train.common.api.Freight.func_70071_h_(Freight.java:135)
	at train.common.entity.rollingStock.EntityFreightWood.func_70071_h_(EntityFreightWood.java:45)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:885)
	at train.common.api.Freight.func_70071_h_(Freight.java:135)
	at train.common.entity.rollingStock.EntityFreightWood.func_70071_h_(EntityFreightWood.java:45)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: tc.Freight Flat Cart Log (train.common.entity.rollingStock.EntityFreightWood)
	Entity ID: 6587
	Entity Name: freightWood
	Entity's Exact location: 178,50, 67,15, 236,50
	Entity's Block location: World: (178,67,236), Chunk: (at 2,4,12 in 11,14; contains blocks 176,0,224 to 191,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['DoomRagnar'/241, l='New World', x=178,41, y=66,00, z=241,01]]
	Chunk stats: ServerChunkCache: 427 Drop: 0
	Level seed: 6891302851873248900
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (148,64,244), Chunk: (at 4,4,4 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2474 game time, 2474 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19025 (now: false), thunder time: 11448 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 217824440 bytes (207 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) 
	UCHIJAAAA	bis{3.1.6} [Back in Slime Mod] (Back In Slime-1.7.10-3.1.6.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum_Core_Lib.1.7.10-2.0.0Beta1.0.jar) 
	UCHIJAAAA	helpfulvillagers{1.2.4} [Helpful Villagers] (helpfulvillagers-1.7.10-1.2.4.jar) 
	UCHIJAAAA	HopperDuctMod{1.3} [Hopper Ducts] (hopperductmod-1.3.jar) 
	UCHIJAAAA	morematerials{0.9.20150214.0} [More Materials] (More-materials-mod-by-localtoast-1.7.10.jar) 
	UCHIJAAAA	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) 
	UCHIJAAAA	tc{4.3.0_002} [Traincraft] (TrainCraft-4.3.0_002.jar) 
	UCHIJAAAA	pixelartist{1.7.10-1.1.2} [pixelartist] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksbuildings{1.7.10-1.1.2} [xtrablocksbuildings] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyadmin{1.7.10-1.1.2} [xtrablocksdiyadmin] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiycloth{1.7.10-1.1.2} [xtrablocksdiycloth] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiydecorations{1.7.10-1.1.2} [xtrablocksdiydecorations] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiydiscs{1.7.10-1.1.2} [xtrablocksdiydiscs] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyfencing{1.7.10-1.1.2} [xtrablocksdiyfencing] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyfood{1.7.10-1.1.2} [xtrablocksdiyfood] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyglass{1.7.10-1.1.2} [xtrablocksdiyglass] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyglow{1.7.10-1.1.2} [xtrablocksdiyglow] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyliquids{1.7.10-1.1.2} [xtrablocksdiyliquids] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiymetal{1.7.10-1.1.2} [xtrablocksdiymetal] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiypanels{1.7.10-1.1.2} [xtrablocksdiypanels] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiypowered{1.7.10-1.1.2} [xtrablocksdiypowered] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiysoundblocks{1.7.10-1.1.2} [xtrablocksdiysoundblocks] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiystone{1.7.10-1.1.2} [xtrablocksdiystone] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiystorage{1.7.10-1.1.2} [xtrablocksdiystorage] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyweapons{1.7.10-1.1.2} [xtrablocksdiyweapons] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiywood{1.7.10-1.1.2} [xtrablocksdiywood] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyxtras{1.7.10-1.1.2} [xtrablocksdiyxtras] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiyfurniture{1.7.10-1.1.2} [xtrablocksdiyfurniture] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiymiscmodels{1.7.10-1.1.2} [xtrablocksdiymiscmodels] (XtraBlocks-1.7.10-1.1.2.jar) 
	UCHIJAAAA	xtrablocksdiytombs{1.7.10-1.1.2} [xtrablocksdiytombs] (XtraBlocks-1.7.10-1.1.2.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['DoomRagnar'/241, l='New World', x=178,41, y=66,00, z=241,01]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
"

**Comment by NitroxydeX** [comment] 2017-01-17 23:11
Update Railcraft.

Duplicate of #135

**Closed as completed by NitroxydeX** 2017-01-17 23:11 UTC
Labels: duplicate, invalid
