### ISSUE TITLE
Slope Not working properly 

### ISSUE THREAD

**Issue by Conjan0711** [EternalBlueFlame/Traincraft-5#175] opened 2016-09-25 05:41 UTC
for version 1.7.10 latest

the slope in traincraft is not working well when Im using trains they pass through the slope and gets stuck how can we fix the issue?

**Comment by NitroxydeX** [comment] 2016-09-25 11:26
duplicate of #157 
we know that slopes are buggy when using different slopesizes directly behind eachother.

**Closed as completed by NitroxydeX** 2016-09-25 11:26 UTC
