### ISSUE TITLE
Going up slopes

### ISSUE THREAD

**Issue by andusarus** [EternalBlueFlame/Traincraft-5#249] opened 2017-02-15 20:51 UTC
whenever i go up a slope, my train turns and begins to go in the opposite direction. 

This is the slope:
![2017-02-15_20 50 26](https://cloud.githubusercontent.com/assets/25803990/22994883/76a1bafe-f3c0-11e6-86f5-56d0fe773371.png)

**Comment by NitroxydeX** [comment] 2017-02-15 22:56
Duplicate of #216

**Closed as completed by NitroxydeX** 2017-02-15 22:56 UTC
Labels: duplicate
