### ISSUE TITLE
Crash Traincraft 

### ISSUE THREAD

**Issue by IamKuba9** [EternalBlueFlame/Traincraft-5#418] opened 2018-08-21 07:49 UTC
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 18.08.18 02:29
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
 at net.minecraft.client.particle.EffectRenderer.func_78867_a(EffectRenderer.java:250)
 at train.common.entity.rollingStock.EntityTracksBuilder.playMiningEffect(EntityTracksBuilder.java:774)
 at train.common.entity.rollingStock.EntityTracksBuilder.harvestBlock_do(EntityTracksBuilder.java:742)
 at train.common.entity.rollingStock.EntityTracksBuilder.digAwayXAxis(EntityTracksBuilder.java:1081)
 at train.common.entity.rollingStock.EntityTracksBuilder.digBuilder(EntityTracksBuilder.java:969)
 at train.common.entity.rollingStock.EntityTracksBuilder.func_70071_h_(EntityTracksBuilder.java:175)
 at net.minecraft.world.World.func_72866_a(World.java:2070)
 at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
 at net.minecraft.world.World.func_72870_g(World.java:2034)
 at net.minecraft.world.World.func_72939_s(World.java:1887)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
 at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
 at net.minecraft.client.particle.EffectRenderer.func_78867_a(EffectRenderer.java:250)
 at train.common.entity.rollingStock.EntityTracksBuilder.playMiningEffect(EntityTracksBuilder.java:774)
 at train.common.entity.rollingStock.EntityTracksBuilder.harvestBlock_do(EntityTracksBuilder.java:742)
 at train.common.entity.rollingStock.EntityTracksBuilder.digAwayXAxis(EntityTracksBuilder.java:1081)
 at train.common.entity.rollingStock.EntityTracksBuilder.digBuilder(EntityTracksBuilder.java:969)
 at train.common.entity.rollingStock.EntityTracksBuilder.func_70071_h_(EntityTracksBuilder.java:175)
 at net.minecraft.world.World.func_72866_a(World.java:2070)
 at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
 at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
 Entity Type: tc.Tracks Builder (train.common.entity.rollingStock.EntityTracksBuilder)
 Entity ID: 0
 Entity Name: Tracks Builder
 Entity's Exact location: 1054,05, 64,96, 458,50
 Entity's Block location: World: (1054,64,458), Chunk: (at 14,4,10 in 65,28; contains blocks 1040,0,448 to 1055,255,463), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
 Entity's Momentum: 0,03, -0,04, 0,00
Stacktrace:
 at net.minecraft.world.World.func_72939_s(World.java:1887)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
 Level name: tc3
 All players: 0 total; []
 Chunk stats: ServerChunkCache: 643 Drop: 0
 Level seed: 1643627684657206657
 Level generator: ID 00 - default, ver 1. Features enabled: true
 Level generator options: 
 Level spawn location: World: (48,64,256), Chunk: (at 0,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
 Level time: 44622 game time, 11806 day time
 Level dimension: 0
 Level storage version: 0x04ABD - Anvil
 Level weather: Rain time: 69706 (now: false), thunder time: 106380 (now: false)
 Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
 at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
 Minecraft Version: 1.7.10
 Operating System: Windows 8.1 (amd64) version 6.3
 Java Version: 1.8.0_181, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 92569896 bytes (88 MB) / 345464832 bytes (329 MB) up to 1038876672 bytes (990 MB)
 JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
 FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
 UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
 UCHIJAAAA Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
 UCHIJAAAA tc{4.4.0_017} [Traincraft] (Traincraft-4.4.0_017.jar) 
 GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
 Profiler Position: N/A (disabled)
 Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 Player Count: 0 / 8; []
 Type: Integrated Server (map_client.txt)
 Is Modded: Definitely; Client brand changed to 'fml,forge'﻿

**Comment by cool9535** [comment] 2018-08-21 09:57
You already reported this error once, no need to do it twice, I'm sure the devs will look into it later today, it's an issue with the Tracks Builder and it should've been fixed in the next update, also, the error has been reported several times before, please have patience and wait for the devs to respond to your first report, thanks.

**Comment by IamKuba9** [comment] 2018-08-21 11:49
thanks

**Comment by IamKuba9** [comment] 2018-08-21 11:54
i got this problem with other mods. game crashing when i try open world

**Comment by IamKuba9** [comment] 2018-08-21 12:07
My sister got this same launcher version of tc and forge and she haven't got crash

**Comment by cool9535** [comment] 2018-08-21 17:06
Probably because she hasn't used the tracks builder yet..

**Comment by EternalBlueFlame** [comment] 2018-08-21 19:56
It seems to be a track builder bug with particles.
Honestly I can't even guess what's going wrong here aside from it either being an invalid block cast for some reason, maybe a world bug that caused an invalid ID, or the fact the vanilla particle system is absolute trash. 
Come to think of it, I don't think this is the first time this issue has crossed my desk either....

I'll try the invalid cast option, because straight up removing the entire mining particle effect is the only other option here.

**Comment by IamKuba9** [comment] 2018-08-21 20:24
So I have to remove these mining particles?

**Comment by EternalBlueFlame** [comment] 2018-08-21 20:32
There's nothing you can do about it. It's an error in the code.
Whether it's my end or minecraft's, I have no clue.

If you have any experience in java you can try to build the latest source and see if it's fixed, but otherwise until the next release the best you can do is avoid using the trackbuilder.
The 017 version is pretty buggy anyway, there will be a LOT of fixes for it in 018, which isn't released yet.

Railcraft has their own version as an alternative meantime.

**Comment by IamKuba9** [comment] 2018-08-21 20:33
@cool9535 my sister used him for few times

**Comment by IamKuba9** [comment] 2018-08-21 20:36
@EternalBlueFlame i can't join world with other mods . like with tc

**Comment by EternalBlueFlame** [comment] 2018-08-21 20:40
Well either way, until the next release, your best option is just to avoid using the trackbuilder, because that's where the issue is coming from.

**Comment by IamKuba9** [comment] 2018-08-21 20:45
I can't use him because world is not loading with traincraft and other mod mcheli talldors and flans mod 4.1 i want play with mcheli and talldors and flans mod but world is not loading what i should do to play with these mods without tc

**Comment by zwamdurkel** [comment] 2018-08-21 20:46
Honestly, those mods together are bound to crash
I've been able to run tc and mcheli together without problems, but flans always causes issues for me

**Comment by IamKuba9** [comment] 2018-08-21 20:55
world without mods. too didn't loading

**Comment by EternalBlueFlame** [comment] 2018-08-21 21:19
In that case, you'll have to find the area that the trackbuilder was in when it crashed, and use MCEdit or the like to delete the entities in the chunk.
According to the log it should be located roughly around 1054X ,64Y, 458Z.

**Comment by IamKuba9** [comment] 2018-08-21 21:27
that's my last crash
--
// Sorry :(

Time: 21.08.18 13:58
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/ICraftingHandler
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/ICraftingHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.ICraftingHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 54045568 bytes (51 MB) / 198881280 bytes (189 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UE	TC{4.2.1_012} [Traincraft] (traincraft-4.2.1_011.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4600'

**Comment by EternalBlueFlame** [comment] 2018-08-21 21:38
That crash is from using the wrong version of Traincraft. (4.2.1 isn't even for 1.7.10)

It may also help with some other unrelated problems if you updated to forge 1614 (1.7.10 latest).

**Comment by IamKuba9** [comment] 2018-08-21 22:09
what if i removed this world ?

**Comment by IamKuba9** [comment] 2018-08-21 22:52
problem is with tracks builder

---- Minecraft Crash Report ----
// Don't do that.

Time: 22.08.18 00:50
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 249906368 bytes (238 MB) / 860618752 bytes (820 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	mcheli{1.0.4} [MC Helicopter] (mcheli) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: Forge 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [TXT MaltiYT, SUPER TXT, §cZytko TXT FOR KAMPER §230K]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by IamKuba9** [comment] 2018-08-22 02:20
i must remove this area?

**Comment by IamKuba9** [comment] 2018-08-22 03:30
last crash

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 22.08.18 05:29
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 96003152 bytes (91 MB) / 438542336 bytes (418 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	mcheli{1.0.4} [MC Helicopter] (mcheli) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [TXT MaltiYT, SUPER TXT, §cZytko TXT FOR KAMPER §230K]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by EternalBlueFlame** [comment] 2018-08-22 03:56
I can't even guess what you did to cause those two crashes, that's not even related to a mod.

**Comment by IamKuba9** [comment] 2018-08-22 08:54
i don't now too when i start playing with traincraft and mcheli then game crashing even without mods
what i should do??

**Comment by EternalBlueFlame** [comment] 2018-08-22 14:05
I checked some online resources for the classes throwing the issue and it looks like your render distance is too high, try changing it to 16 or less before you load a world and see if it boots then.

**Comment by IamKuba9** [comment] 2018-08-22 18:43
OMG WORK THANKS BRO <3

**Comment by IamKuba9** [comment] 2018-08-22 18:55
oh, and i have 1 more problem when play 1h or more i can't enter the train

**Comment by EternalBlueFlame** [comment] 2018-08-22 19:04
That is a permissions bug, it's worse in LAN and singleplayer, there will be some extra patches for it in 018.

In 017 and older the only thing you can do is break it and re-place it.

**Comment by IamKuba9** [comment] 2018-08-22 19:13
I can't join LAN server now

Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException:
   the received string length is longer than maximum allowed (17>16)

**Comment by EternalBlueFlame** [comment] 2018-08-22 19:34
That's a bug related to a bukkit plugin trying to deal with an entity that has a name linger than 16 characters.

**Comment by IamKuba9** [comment] 2018-08-22 19:44
What i can do?

**Comment by EternalBlueFlame** [comment] 2018-08-22 19:45
dig through your plugins and see what might be causing it.
TabDeco, Multiverse, Minigames and UltraHardcore are some of the best known for causing the issue.

Emphasis on plugins, not mods, they are different things in different folders.

**Comment by IamKuba9** [comment] 2018-08-22 19:46
Where i can find this?

**Comment by IamKuba9** [comment] 2018-08-22 19:46
In what folder?

**Comment by EternalBlueFlame** [comment] 2018-08-22 19:46
usually the plugins folder in your server's folder

**Comment by IamKuba9** [comment] 2018-08-22 19:47
In saves?

**Comment by EternalBlueFlame** [comment] 2018-08-22 19:48
no it would be in the same folder as mods usually.

**Comment by IamKuba9** [comment] 2018-08-22 19:49
i what now?

**Comment by EternalBlueFlame** [comment] 2018-08-22 19:50
![image](https://user-images.githubusercontent.com/9969122/44486981-ad339700-a61a-11e8-9a12-a5718cbccb30.png)

**Comment by IamKuba9** [comment] 2018-08-22 19:50
i got LAN server

**Comment by IamKuba9** [comment] 2018-08-22 19:51
I got LAN server

**Comment by IamKuba9** [comment] 2018-08-22 20:03
i got to long nickname and this is problem

**Comment by EternalBlueFlame** [comment] 2018-08-22 20:07
strange that issue usually only happens in relation to plugins.

**Comment by IamKuba9** [comment] 2018-08-23 02:40
what is that mod? https://www.youtube.com/watch?v=-thlRxI-etM (Polish) 
time 18:26

**Closed as completed** 2018-08-23 03:12 UTC
Labels: bug
