### ISSUE TITLE
New tracks maybe?

### ISSUE THREAD

**Issue by melindaendv** [EternalBlueFlame/Traincraft-5#173] opened 2016-09-24 20:38 UTC
I have some ideas for new track types:

45 deg straights AKA diagnol track (short, medium and long)
Half curves (to connect to the diagonal tracks)
Y Switch - I have had MANY occasions where this would be extremely helpful
Double track crossover switch to change from one track to another
45 deg diamond
Single and double slips
Railyard switches (the diagonal track with a switch to create yard lanes more efficiently)
Hump Yard Slopes (Just steeper slopes than the regular ones so cars can coast down easier)
Maybe some basic triggering tracks that will fire a redstone signal when a train is on them.

I don't know how hard any of this would be to create but these are just ideas.

**Comment by Czarified** [comment] 2016-09-24 22:05
There's a thread for this already. Maybe you should take a look in there? People much more knowledgeable than me discuss the difficulties/current-impossibility of diagonal track.

**Comment by melindaendv** [comment] 2016-09-25 01:55
oh thanks I did not know that

**Comment by NitroxydeX** [comment] 2016-09-25 11:22
duplicate of #48

**Closed as completed by NitroxydeX** 2016-09-25 11:22 UTC
