### ISSUE TITLE
Server frozen with Traincraft 005 Update!

### ISSUE THREAD

**Issue by MacTirom** [EternalBlueFlame/Traincraft-5#222] opened 2016-12-12 21:31 UTC
Since the TC 005, our server is just hanging out every few hours, they all fly out and it is nothing more than "pinging" in the console happens nothing at all and if the server does not give a restart command simply remains in this "frozen" State. There are no crash reports because the server does not crash. But this has only been so since the TC 005.

He takes a lot of time to realize that he should start!
See:

Send command: save-all
Send command: stop
Send command: exit
Send command: stop
Send command: exit
Send command: stop
Send command: exit

**Comment by NitroxydeX** [comment] 2016-12-12 21:53
We need a log file (not crash) of this. Otherwise you could put Sampler from Player into the mods folder. If the Server is 30 Seconds in Freeze state it creates a dumb but you need to send this dumb to Player first. Only he can read the content of it. But he will find the bug.

**Comment by EternalBlueFlame** [comment] 2016-12-12 22:58
if you are on java 1.7 (which most server hosts are) this will happen because there's not enough perm space. it can be fixed with the augment `-XX:MaxPermSize=512`
It can also be fixed by updating to java 1.8.
I had to fix that issue for another server that I frequent.

If you're gonna go to the excess of updating though, update to JDK 1.8 because things run significantly smoother with that due to the ability to use the `-server` augument.

**Comment by MacTirom** [comment] 2016-12-12 23:04
The server is in java 8 since the beginning.
but this maxPermSize=96
i must set it to 512 or?

**Comment by EternalBlueFlame** [comment] 2016-12-12 23:07
If its in java 8 and still doing that, its not a perm size issue...
Double check with other mods you have on the server, because that usually only happens when something is conflicting or making a memory leak.

**Comment by MacTirom** [comment] 2016-12-12 23:09
hmmm, and if it is the system? Our server console is spammed by this: 
[00:02:13 WARN]: Error occured during retriving version
java.lang.Throwable
at kcauldron.KLog.log(KLog.java:30) [KLog.class:1.7.10-R0.1-SNAPSHOT]
at kcauldron.KLog.warning(KLog.java:41) [KLog.class:1.7.10-R0.1-SNAPSHOT]
at kcauldron.updater.KVersionRetriever.uncaughtException(KVersionRetriever.java:114) [KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:94) [KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
at kcauldron.updater.KVersionRetriever.run(KVersionRetriever.java:69) [KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalStateException: Status code isn't OK
... 3 more

**Comment by MacTirom** [comment] 2016-12-12 23:11
We have 3 mods Buildcraft 7.1.18, Railcraft 9.12.2.0 and Traincraft 4.3.0_005
idk how i can check this...

**Comment by EternalBlueFlame** [comment] 2016-12-12 23:16
that would do it. getting console spammed is basically the equivalent of a memory leak and would cause the problem.

looks like its caused by the version of KCauldron you're running.. let me double check my version because mine only warns on start.
here we go, this was the place. the main download should get you a working one. Be sure to her KCauldron and not the bootstrap, the bootstrap was always a problem for KCauldron.
[https://prok.pw/downloads.html](https://prok.pw/downloads.html)

**Comment by MacTirom** [comment] 2016-12-12 23:27
huh? I cannot download their. Then comes a circle, which then disappears again. And more does not happen..
This is the reason why we had to download this here: https://sourceforge.net/projects/cauldron-unofficial/files/kcauldron/

**Comment by MacTirom** [comment] 2016-12-12 23:29
Do you can download their on prok.pw ? I cannot.

**Comment by EternalBlueFlame** [comment] 2016-12-12 23:53
ah, well in that case, try this one. i had to double check the build i use to be sure.
https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.201/

**Closed as completed** 2016-12-18 23:04 UTC
Labels: invalid
