### ISSUE TITLE
TC Tracks not compatible with railcraft

### ISSUE THREAD

**Issue by OLastFight** [EternalBlueFlame/Traincraft-5#302] opened 2017-08-01 09:47 UTC
I am using Traincraft 4.3.2_009 and Railcraft 9.12.20

**Comment by OLastFight** [comment] 2017-08-01 09:49
Umm it should be Railcraft 9.12.2.0

**Comment by NitroxydeX** [comment] 2017-08-01 15:32
1. What exactly isn't working?
2. What do you want to achieve?
3. Steps to reproduce this issue

**Comment by OLastFight** [comment] 2017-08-01 17:13
I think i found the problem
1.When i use Traincraft rail (90 degrees Large & Medium Switch) the Routing Switch Motor wont work even the destination is correct.However,the motor work when is not traincraft rail.
2.Use Traincraft rail for routing with Routing Switch Motor(The curved rail looks beautiful ._.)
3.1Make a rail system which got 90 degrees Large/Medium switch rail
3.2Get a routing track and a routing switch motor.Place motor for the 90 degrees rail.
3.3. Get a routing table and a golden ticket.Set both items to same destination.Then place the golden ticket in routing track and turn it on.Place routing table in the motor.(Then it should switch when after it pass the routing track in theory)
3.4 Run a train and let it pass a routing track which is on.And then the routing switch motor doesnt work 
Sorry for my poor English.Idk do i explain it well

**Comment by NitroxydeX** [comment] 2017-08-01 17:36
Well, it's true. Railcraft switches and signaling isn't compatible with our tracks and it won't be fixed until the rewrite.

Railcraft signaling theoretically only works with our tracks in Minecraft 1.10.2+ since the author wanted to change how tracks are detected.

**Closed as completed by NitroxydeX** 2017-08-01 17:36 UTC
Labels: invalid, question, rewrite

**Comment by OLastFight** [comment] 2017-08-01 17:37
Oh.Thats sad
