### ISSUE TITLE
Rolling stock breaking appart , steam and diesel locomotives are just Loco

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#201] opened 2016-10-27 23:16 UTC
cb2e72f3fb2d5128938178a5a1658bbf09276aeb breaks attaching on everything . Locomotives can now 
- pull wheelies
- if they don't like being at the front of the train , they just move anywhere they want in the freight chain
- some time they like to just move side ways because it's fun to sway.
- If a locomotive decides to quit  smoking the smoke from the exhaust can be found on another car  .
  Get the jest of it ? Its just a dance of chaos !

**Comment by EternalBlueFlame** [comment] 2016-10-27 23:52
Probably a mod conflict, because these changes dont effect any of those systems.
We'd also need details how to replicate the issues if it's not a mod conflict.

**Comment by Tsoccerguy3** [comment] 2016-10-28 01:50
Here is access to my One-drive , //link removed by eternal// , Everything in the Traincraft 5 beta directory is my testing environment , take everything including the Map and my last compile . In the Map there are a few test tracks . It is possible , it is a problem from a previous commit , I didn't compile commit since early last week

**Comment by EternalBlueFlame** [comment] 2016-10-28 02:39
"and my last compile" so by that im guessing this isnt a release version? even though we are at release stage?
Also even for testing purposes, i need to constantly state, its against the license to distribute the jar file.

**Comment by Tsoccerguy3** [comment] 2016-10-28 02:58
Good point , forgot that more than just you will see this . Test the map . it has some trains running that will eventually do something

**Comment by Tsoccerguy3** [comment] 2016-10-28 03:10
![2016-10-27_18 37 02](https://cloud.githubusercontent.com/assets/22108822/19793412/7724cd0e-9c9a-11e6-876b-7e4688cb1d49.png)
![2016-10-27_23 04 30](https://cloud.githubusercontent.com/assets/22108822/19793484/be8dc448-9c9a-11e6-9e71-d08900a4fa9f.png)
![2016-10-27_23 05 22](https://cloud.githubusercontent.com/assets/22108822/19793483/be87a180-9c9a-11e6-9ded-c9ecbe324c03.png)

**Comment by NitroxydeX** [comment] 2016-10-28 12:03
Well. It is always possible that this is not caused by TC itself. Make sure you got our latest release version and test this on a new map only with TC. We actually need the WHOLE steps to reproduce the error.

**Comment by EternalBlueFlame** [comment] 2016-10-28 16:50
Given theres no steps to replicate the errors, the only one i can get to happen is the chunkloading issue, using chicken chunks will almost always prevent the error. The sad part is that chicken chunks has become rather unreliable over the years, it _was_ the go-to chunkloading mod back in 1.6.4.

I just had an idea for our own chunkloader that might not have a significant impact on performance, and would prevent these issues, even obsolete any need for chicken chunks.

the error in question:
http://i.imgur.com/4vlAJTZ.png

**Comment by EternalBlueFlame** [comment] 2016-11-02 19:00
UPDATE: well apparently the fact chicken chunks prevents this error usually is an odd coincidence because we actually don't use that part of it, all of chicken core we use is for NEI.

I really don't know how to fix this error and it has plagued me since i started the port.

But long run, I can confirm the issues in this thread are in fact a duplicate of #196 
and not caused by [https://github.com/EternalBlueFlame/Traincraft-5/commit/cb2e72f3fb2d5128938178a5a1658bbf09276aeb](https://github.com/EternalBlueFlame/Traincraft-5/commit/cb2e72f3fb2d5128938178a5a1658bbf09276aeb)

**Closed as completed by EternalBlueFlame** 2016-11-02 19:00 UTC
