### ISSUE TITLE
Incompatibility with Railcraft?

### ISSUE THREAD

**Issue by dymondy2k** [EternalBlueFlame/Traincraft-5#184] opened 2016-09-28 21:37 UTC
I receive the following error when I try to run Minecraft with Railcraft and Traincraft installed. If I remove one or the other it will load fine. It seems to be a recipe issue but I have tried everything in the Railcraft configs to disable it? Any ideas short of removing Railcraft. I've used quite a bit of their items so not excited about that option but on the otherhand have been waiting for Traincraft for 1.7 for years!!

Invalid shaped ore recipe: #A#, #B#, #C#, #, null, A, null, B, net.minecraft.block.BlockChest@2e8a1ab4, C, train.common.items.ItemPart@17a0afff, 8xtile.railcraft.track@11385
    at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:116)
    at train.common.core.plugins.PluginRailcraft.registerRecipes(PluginRailcraft.java:25)
    at train.common.core.plugins.PluginRailcraft.init(PluginRailcraft.java:19)
    at train.common.core.TrainModCore.ModsLoaded(TrainModCore.java:16)
    at train.common.Traincraft.postInit(Traincraft.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by NitroxydeX** [comment] 2016-09-28 23:07
duplicate of #165 
We've already fixed that. Don't use vanilla recipes when you have 
Railcraft installed otherwise it will crash.

Fixed in _004 when it's out. But you won't get any of our added tracks then.

**Closed as completed by NitroxydeX** 2016-09-28 23:07 UTC
Labels: duplicate
