### ISSUE TITLE
[4.3.1_007] Linking cart problem

### ISSUE THREAD

**Issue by ccgfok** [EternalBlueFlame/Traincraft-5#250] opened 2017-02-16 14:51 UTC
It started when I quit and re-login into game, it confusioned.
To re-produce:
1. Give your own loco and some cart.
2. Make link between it, like this:
![2017-02-16_21 33 58](https://cloud.githubusercontent.com/assets/11695493/23025636/31af6f28-f491-11e6-9202-e47cb7f2889c.png)
3. Quit, and then re-login, and cart will float, except locomotive:
![2017-02-16_21 34 18](https://cloud.githubusercontent.com/assets/11695493/23025683/55f120ca-f491-11e6-964b-830c73adfc2b.png)
* For addition, if I make longer train, and then quit game and then re-login this world, it make a confusion.
![2017-02-16_21 38 43](https://cloud.githubusercontent.com/assets/11695493/23025739/824af38a-f491-11e6-8cd0-9395c133d659.png)
![2017-02-16_21 38 51](https://cloud.githubusercontent.com/assets/11695493/23025749/861ade26-f491-11e6-9bd7-da508e4f3e85.png)

**Comment by TheSpareAce** [comment] 2017-02-16 17:23
A temporary way to fix this is to detach all carts from each other (Best solution with freight carts carrying cargo currently) or you could break down passenger carts. The bug used to be worse before version 6.

**Comment by EternalBlueFlame** [comment] 2017-02-18 01:08
The issue is less about linking and more about how the save data is managed, 1.6.4 methods don't work worth a crap in 1.7.10, and there's no way to transition the values to a better method that is reliable. Especially not without corrupting worlds.

Now I could be wrong, someone with more experience may know a way. But such a person has yet to offer assistance.

**Comment by EternalBlueFlame** [comment] 2017-05-03 06:10
just a heads up, this should be fixed in 009 with the chunkloading changes (i hope).
it will need testing though.

**Comment by EternalBlueFlame** [comment] 2018-05-21 16:06
Well clearly this has not been fixed thus far but there are some changed in 017 that might.
One seemingly major reason would have been that trains and stock often got the internal id of "-1" meaning they couldn't identify eachother, I replaced this with forge's inbuilt entity ID system.
Not exactly foolproof like a UUID system, since the entity ID system isnt designed to persist between sessions, based on luck after a restart it is possible to place something and it wight have an already used ID, but should at least fix the issue to a far more usable point than it's been.
https://github.com/EternalBlueFlame/Traincraft-5/commit/aa4d72880f00bfa503a97c21e82e8339286579a7

**Comment by TCCHS105** [comment] 2018-07-31 01:24
Just a FYI..but from what i have found this issue happens less often if u use Railcraft's crowbar to couple trains as opposed to the Stake that comes with TC. Use the crowbar to couple TC rolling stock and the stake to attach it to the locomotive. I found when i do that the trains glitch less often.

**Closed as completed** 2024-08-01 01:31 UTC
Labels: bug, rewrite
