### ISSUE TITLE
All linked trains fall apart on train leaving visual line of site and logging off

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#367] opened 2018-02-18 17:40 UTC
Report on current build state of TC
Just compiled today's code (2018 , Feb , 18) for my kids . They played around with it for a few hours . They found no Engine/Car configuration of any length that would stay together. Once a train leaves your line of site it breaks apart . If a train is turned off and sitting and you leave the area it breaks apart . log off and back on it's broken . Tested by it self . I imported the test map into MCEdit to check for ghost blocks that might interfere and found none . My kids found the mod unusable in its current state . 

![2018-02-05_09 35 22](https://user-images.githubusercontent.com/22108822/36354809-cb253d7c-14a7-11e8-8572-01c8f1719183.png)
![2018-02-05_20 06 51](https://user-images.githubusercontent.com/22108822/36354811-d14b18ac-14a7-11e8-9a08-32c5cb793806.png)
![2018-02-05_20 07 08](https://user-images.githubusercontent.com/22108822/36354815-d86be544-14a7-11e8-8894-ff880ba7aa0e.png)
![2018-02-16_20 59 57](https://user-images.githubusercontent.com/22108822/36354818-de899232-14a7-11e8-8465-49f2a3d58ba5.png)
![2018-02-16_21 02 45](https://user-images.githubusercontent.com/22108822/36354821-e23b50e6-14a7-11e8-95bc-59f445cde5c9.png)
![2018-02-05_09 35 09](https://user-images.githubusercontent.com/22108822/36354805-c10384ac-14a7-11e8-9390-c8de32575556.png)

**Comment by EternalBlueFlame** [comment] 2018-02-19 22:29
duplicate of #250

**Closed as completed by EternalBlueFlame** 2018-02-19 22:29 UTC
