### ISSUE TITLE
Bug with Trains

### ISSUE THREAD

**Issue by MacTirom** [EternalBlueFlame/Traincraft-5#227] opened 2016-12-30 18:24 UTC
I drive with the train, go afk for eating, come back and then this????
![2016-12-30_19 22 50](https://cloud.githubusercontent.com/assets/16389466/21570344/72eb181c-cec5-11e6-8d13-90818d7f69c6.png)

**Comment by EternalBlueFlame** [comment] 2016-12-31 22:14
More likely than not you were going to fast and derailed at the curve of the parallel.
Or it's a duplicate of [https://github.com/EternalBlueFlame/Traincraft-5/issues/196](https://github.com/EternalBlueFlame/Traincraft-5/issues/196)

**Closed as completed by EternalBlueFlame** 2016-12-31 22:14 UTC
