### ISSUE TITLE
Tracks can only be crafted with steel instead of iron

### ISSUE THREAD

**Issue by SuperKingJulian2** [EternalBlueFlame/Traincraft-5#285] opened 2017-05-15 15:52 UTC
Shouldnt be the tracks be out of iron only since the new update?
...well they are out of Steel only now... i hope thats wrong...

Also Changelog told that tracks should be now craftable out of vanilla track... it isnt possible yet since you only can turn Traincraft Track into vanilla and not the other way around...

**Comment by NitroxydeX** [comment] 2017-05-15 16:02
https://ntrxydx.net/nOET3 Whats the problem?

~Well Eternal seem to have messed up the correct direction of the recipe for vanilla/TC convert. whooops.~

**Comment by SuperKingJulian2** [comment] 2017-05-15 16:05
well i am right now with it is only possible with steel or not lol i am irritated a little xD since the recipe defenetly shows that i have to use steel...

also whats about the vanilla track problem?

**Comment by SuperKingJulian2** [comment] 2017-05-15 16:06
well i am right now with it is only possible with steel or not lol i am irritated a little xD since the recipe defenetly shows that i have to use steel...

also whats about the vanilla track problem?

**Comment by NitroxydeX** [comment] 2017-05-15 16:15
Do you have to use steel for ALL 6 positions? Because it should be like on the screenshot. Iron only.

~Well the Vanilla track problem is just a mistake on our end. Will be fixed with the next update.~

It's just not registered into NEI. Crafting is possible in the middle slot of our Train Workbench with Vanilla Tracks to TC Tracks.

**Comment by EternalBlueFlame** [comment] 2017-05-15 21:09
This may or may not have been fixed after 009, but the recipe for the small straight track is as follows:
`TrainCraftingManager.instance.addRecipe(new ItemStack(ItemIDs.tcRailSmallStraight.item, 16),  "I I", "IPI", "I I", Character.valueOf('P'), plankItem, Character.valueOf('I'), Items.iron_ingot );// small straight track`

More likely than not it's an NEI bug, because I never updated that stuff, never understood how our stupid recipes interact with it. upon looking again, I still don't understand it. The book works fine though, so, there's that.

**Comment by SuperKingJulian2** [comment] 2017-05-21 09:03
OK it IS possible to craft Traincraft track out of vanilla tracks, anyways i miss the recipe in the crafting guide too, may add it... ?
![2017-05-21_10 57 57](https://cloud.githubusercontent.com/assets/24599279/26282605/d2c38e86-3e14-11e7-8895-f727372486c3.png)
Like i said tracks are only craftable with Steel:
![2017-05-21_10 59 04](https://cloud.githubusercontent.com/assets/24599279/26282624/103bf5e6-3e15-11e7-9ac5-e0e1035b6cb5.png)
![2017-05-21_10 59 28](https://cloud.githubusercontent.com/assets/24599279/26282625/136a371e-3e15-11e7-905d-d5c76ae2ca16.png)
With fixing this and adding the vanilla track recipe to the crafting guide this can be closed.

**Comment by NitroxydeX** [comment] 2017-05-21 17:55
Recipes are added automatically to the crafting guide. It seems to be the same fail why it is not registered into NEI/JEI

**Comment by NitroxydeX** [comment] 2017-05-21 18:17
About the Iron thing. This got fixed after the 009 release. try Steel only otherwise it's not working in general caused by a bug in our planks reference.

**Comment by EternalBlueFlame** [comment] 2017-05-21 18:45
ty for the reminder, i need to add ore directory support for iron.

**Closed as completed** 2017-10-05 22:13 UTC
Labels: wait for user input
